default:
  adapter: mysql2
  database: Cats
  username: sinatra
  password: password
  host: localhost
development:
  adapter: mysql2
  database: Cats
  username: sinatra
  password: password
  host: localhost
production:
  adapter: mysql2
  database: Cats
  username: sinatra
  password: password
  host: localhost